env:
  - XDEBUG_MODE=coverage

language: php

php:
  - 7.4
  - 8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan env

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

# Monitor only these branches
branches:
  only:
  - master
  - dev