name: Browser extension bug report
description: Something is not working as expected with the browser extension
title: "[WebExt]: "
labels: ["triage", "webextension"]
projects: Bubka/1
body:
  - type: input
    id: 2fauth_version
    attributes:
      label: 2FAuth version
      description: The version of the 2FAuth server bound to the browser extension
      placeholder: ex. 5.3.0
    validations:
      required: true
  - type: input
    id: webextension_version
    attributes:
      label: Extension version
      description: The version of the browser extension
      placeholder: ex. 1.0.2
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: Browsers that have the extension installed and on which you are experiencing the problem
      multiple: true
      options:
        - Firefox (or derivatives)
        - Chrome (or derivatives)
        - Microsoft Edge
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe what is happening and how to reproduce it. Also tell us what did you expect to happen. Screenshots are welcome.
    validations:
      required: true
  - type: textarea
    id: error_logs
    attributes:
      label: Error & Logs
      description: >-
        Any execution data you think may help understand and solve your problem: Error message, stack trace, error/access logs from the web server.
      placeholder: 2FAuth logs can be found in [2FAuth_install_directory]/storage/logs/
      render: shell
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: >-
        Any information you think may give a good idea of your setup: Configurations, settings, network, proxies.
      placeholder: >-
        The /about page of your 2FAuth instance displays environment variables,
        user preferences and admin settings you can easily copy and past here as a good starting point
  - type: checkboxes
    id: context
    attributes:
      label: Containerization
      description: Is your 2FAuth instance running from a container?
      options:
        - label: Docker
          required: false
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description: Any additional information you would like to submit
